### ISSUE TITLE
Egal, welchen Typ man bei der Buchung wählt: es werden beide jeweils aufgelistet

### ISSUE THREAD

**Issue by ipreusshock** [isarwatt/klink-issues-public#10]
**Product**
Frontend 

**Describe the bug**
Unterkünfte oder Räume - es werden jeweils Kloster Schledorf,  der Gemeinschaftsraum und das Gästeappartemnet gelistet
Preis für Gemeinschaftsraum= 0 € pro NACHT

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Device: [e.g. iPhone6 or PC/Mac]
 - OS & Version: [e.g. iOS 10]
 - Browser & Version [e.g. Firefox 45]

**Additional context**

**Comment by johanneshochholzer** [comment]
Hallo Irene,
Danke für das Feedback.
Der Gemeinschaftsraum wurde als Unterkunft angelegt, daher erscheint er auch in dieser Kategorie.
