### ISSUE TITLE
Uneinheitliche Schreibweise für Gästeapartments // Gästeappartment 

### ISSUE THREAD

**Issue by ipreusshock** [isarwatt/klink-issues-public#11]
**Product**
Frontend

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Device: [e.g. iPhone6 or PC/Mac]
 - OS & Version: [e.g. iOS 10]
 - Browser & Version [e.g. Firefox 45]

**Additional context**

**Comment by johanneshochholzer** [comment]
Das kann über das Verwaltungsfrontend selbst behoben werden.
Bitte melde dich, wenn du es nicht ändern kannst.
