### ISSUE TITLE
Unterscheidung Hausbewohner // externe Wogeno bzw. wagnis Mitglieder

### ISSUE THREAD

**Issue by ipreusshock** [isarwatt/klink-issues-public#12]
**Product**
Frontend

**Describe the bug**
Für beide wird 25 € pro Nacht angegeben. Für externe kostet das Appartemnet jedoch 35 €
Hausbewohner können 4 Monate im Voraus buchen, externe nur 14 Tage vorher. 
Es muss also ein Feld geben, über das man angeben kann, ob man ein Hausbewohner ist und entsprechend muss die Vorausbuchung überprüft werden, ob möglich

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Device: [e.g. iPhone6 or PC/Mac]
 - OS & Version: [e.g. iOS 10]
 - Browser & Version [e.g. Firefox 45]

**Additional context**

**Comment by johanneshochholzer** [comment]
Jeder Nutzer kann selbstständig seine Zugehörigkeit zur Organisation und zum Projekt anfragen.
Bei den Ressourcen können für die Zugehörigkeit verschiedene Preise hinterlegt werden.
Die Plattform kann das abbilden, allerdings müssen die Ressourcen entsprechend konfiguriert werden.
