### ISSUE TITLE
Suche nach Ort/Name fehlerhaft

### ISSUE THREAD

**Issue by ipreusshock** [isarwatt/klink-issues-public#13]
**Product**
Frontend

**Describe the bug**
"Schl" liefert Ergebnis - Suche geht vielleicht nur über den Namen? "Sch" liefert nämlich als Ergebnis auch die GemeinSCHaftsflächen und GemeinSCHaftsraum in München 
"München" liefert kein Ergebnis

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Device: [e.g. iPhone6 or PC/Mac]
 - OS & Version: [e.g. iOS 10]
 - Browser & Version [e.g. Firefox 45]

**Additional context**

**Comment by johanneshochholzer** [comment]
Die Karte ist noch nicht integriert, daher funktioniert noch keine Ortssuche.
kommt mit der nächsten Version.
