### ISSUE TITLE
Ergänzung des Kontos um Adresse und Geburtsdatum liefert falsche Message

### ISSUE THREAD

**Issue by ipreusshock** [isarwatt/klink-issues-public#14]
**Product**
Frontend

**Describe the bug**
![grafik](https://user-images.githubusercontent.com/91162011/134257425-38c3de98-0f2b-4dcd-a0bf-9f25b39d732c.png)

![grafik](https://user-images.githubusercontent.com/91162011/134257577-1c430fa6-3ffd-4cb4-96bc-c28d31c70bba.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Device: [e.g. iPhone6 or PC/Mac]
 - OS & Version: [e.g. iOS 10]
 - Browser & Version [e.g. Firefox 45]

**Additional context**

**Comment by benediktdertinger** [comment]
@ipreusshock Can you please add detailed steps on how to reproduce this?
