### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#17]
**Product**
Frontend (combined with Admin Frontend)

**Describe the bug**
I try to login with my username on frontend and am forwarded to an error page of the Admin backend.

**To Reproduce**
1. Click on "Anmelden"
2. Enter credentials
3. Following Page is shown:
https://verwaltung-staging.klink.app/register
![grafik](https://user-images.githubusercontent.com/75273091/136762755-9b74df7e-f9c0-4ce5-b1ff-4752dcc825e9.png)

**Expected behavior**
Login should lead to user dashboard in Frontend

**Comment by benediktdertinger** [comment]
@johanneshochholzer I'm not able to reproduce this.

**Comment by johanneshochholzer** [comment]
I also can't reproduce any more.
