### ISSUE TITLE
Streamline Detail Page

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#19]
**Product**
Frontend

**Describe the bug**
The headlines for empty fields are shown

**To Reproduce**
1. Open Detail page

**Expected behavior**
Only headlines for text fields are shown when they are filled out by the R admin

**Screenshots**
![grafik](https://user-images.githubusercontent.com/75273091/136764440-c82420a1-8c5a-4b18-b7e8-9c08a6845414.png)

**Comment by benediktdertinger** [comment]
@david-ziegler please hide headlines for undefined text blocks

**Comment by benediktdertinger** [comment]
@david-ziegler 

- [x] Hide headlines and sub headlines if not content
- [x] Add all details from actual resource

**Comment by david-ziegler** [comment]
can we close this? it's done.
