### ISSUE TITLE
Search fields are not cleared after use

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#20]
**Product**
Admin Frontend

**Describe the bug**
I open a field to add e.g. a ressource admin.
The field is still filled with a previous search.

**To Reproduce**
1. Open Organisation / Resource
2. Add Admin
3. Search field is still filled

**Expected behavior**
Search field is empty

**Screenshots**
![grafik](https://user-images.githubusercontent.com/75273091/136764825-6559387a-2c31-4b68-8d82-0678388f223d.png)

**Comment by johanneshochholzer** [comment]
![grafik](https://user-images.githubusercontent.com/75273091/139591400-e93efc9c-965d-4fc7-b8fd-c4fa3bb0602f.png)
Not yet fixed

**Comment by benediktdertinger** [comment]
@johanneshochholzer you can check and close it

**Comment by anjarichard** [comment]
Not reproducible in the current version on staging, so issue will be closed.
