### ISSUE TITLE
Behaviour Booking List

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#22]
**Product**
Admin Frontend

**Describe the bug**
- Button for confirming the booking is missing
- bookings are only shown for R admins
- Booking List is empty even if I have R admin status for resources

**To Reproduce**
1. Open Booking List
2. Create new booking
3. Look at new entry for booking List

**Comment by benediktdertinger** [comment]
@johanneshochholzer I can not reproduce the access problem related to access roles. If I remove my access role for the R but retain the P or O access role(s) (and these were added to the R in manage tab) I still have access.

**Comment by johanneshochholzer** [comment]
I can reproduce it in different ways.

# Case 1: R-Manage-Role
User has R-Manage Role and cannot see any booking:
![grafik](https://user-images.githubusercontent.com/75273091/138559453-692efc95-6294-48ef-b613-e6df9cd22b30.png)
Empty Booking-List
![grafik](https://user-images.githubusercontent.com/75273091/138559493-8c819a8e-063d-4637-8983-b234f3b80e0a.png)
(Maybe this is also caused because the R is only visible for O members, where I don't have management access in this example)

# Case 2: R-Management Role indirectly via O-Management-Role
![grafik](https://user-images.githubusercontent.com/75273091/138559589-df081393-5d5e-4b01-8515-80b0a6826a78.png)
![grafik](https://user-images.githubusercontent.com/75273091/138559607-101df67c-1be7-4462-b2bb-d951ef8d6df6.png)
![grafik](https://user-images.githubusercontent.com/75273091/138559624-88733414-04d2-4aeb-9823-30671b3d1b5d.png)
Empty Booking List
![grafik](https://user-images.githubusercontent.com/75273091/138559646-67d2e1ef-b0ab-493b-9c73-6673a8246500.png)

**Comment by benediktdertinger** [comment]
@johanneshochholzer you can check and close it

**Comment by anjarichard** [comment]
Retest results:

- Case 1: not reproducible anymore. Booking could be seen and confirmed with account which had only management rights for the ressource
- Case 2: not reproducible anymore. Booking could be seen and confirmed with account which had management rights inherited from the organization

Linked to https://github.com/isarwatt/klink-issues/issues/280 - inheritance should discussed again, but this issue will be closed for now
