### ISSUE TITLE
Hide Object ID in Breadcrumb

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#24]
**Product**
Admin Frontend

**Describe the bug**
Hide Object ID in Breadcrumb
Show Object Title instead

![grafik](https://user-images.githubusercontent.com/75273091/136768192-fe22d814-f656-4492-9e1e-31e14d8b51a4.png)

**Comment by benediktdertinger** [comment]
@johanneshochholzer does this have a high priority?

**Comment by johanneshochholzer** [comment]
I moved it to a later version

**Comment by johanneshochholzer** [comment]
Transferred to https://github.com/isarwatt/klink-issues/issues/270
