### ISSUE TITLE
Confirm Booking doesn't work

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#25]
**Product**
Admin Frontend

**Describe the bug**
Booking Confirmation Workflow not working + unclear

**To Reproduce**
1. Booking for room with confirmation needed is done
2. E-Mail is created
![grafik](https://user-images.githubusercontent.com/75273091/136769835-f936c5d0-e592-4c24-876c-75fe0b794e10.png)
3. Click on Accept
4. See 404
![grafik](https://user-images.githubusercontent.com/75273091/136770166-2d257edf-28b3-4484-9ff1-afd4710fcd50.png)

**Expected behavior**
Notification for booking to be confirmed via mail, confirmation in Admin Backend.

**Comment by benediktdertinger** [comment]
Switch to Approve/decline booking via interface instead of email hash links
