### ISSUE TITLE
Colour for non-editable fields might be too transparent

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#26]
**Product**
Frontend

**Describe the bug**
The colour of non-editable fields (e.g. e-mail-adress) makes it hard to read and see that the field contains some value.

![grafik](https://user-images.githubusercontent.com/75273091/137197747-fafa0fcc-feda-4bf2-9ef7-bb80257c2b3f.png)

**Expected behavior**
Is there a different way of showing that a field cannot be edited? Other colour schemes?

**Comment by benediktdertinger** [comment]
@johanneshochholzer we will add a slightly adapted version. Also discussed in: https://github.com/isarwatt/klink-issues-public/issues/33

Let's add more contrast to the text color and use a light grey for the background.

**Comment by johanneshochholzer** [comment]
Sounds good.
