### ISSUE TITLE
(non reproducable) Date picker strange behaviour

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#29]
**Product**
Frontend

**Describe the bug**
The date picker showed a written number instead of a number.
I couldn't reproduce the error, but see screenshot:

![grafik](https://user-images.githubusercontent.com/75273091/137198890-ac71d7c8-aa42-4651-b227-001d90b8f435.png)

**Comment by benediktdertinger** [comment]
@johanneshochholzer Can you please give us details about your OS (+version) and Browser (+version)?

**Comment by johanneshochholzer** [comment]
requested from user

**Comment by johanneshochholzer** [comment]
I got these informations:
Version des Betriebssystems, : Windows 10 Pro/ 21H1/ 64-Bit-Betriebssystem, x64-basierter Prozessor
Version des Browsers: Microsoft Edge( Version 95.0.1020.30 (Offizielles Build) (64-Bit)
Version des Browsers: Google Chrome( Version 95.0.4638.54 (Offizieller Build) (64-Bit))

**Comment by benediktdertinger** [comment]
@johanneshochholzer can you still reproduce this?

**Comment by johanneshochholzer** [comment]
no.
