### ISSUE TITLE
404 when resource is only visible for organisation

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#3]
**Product**
Frontend

**Describe the bug**
A resource that is only visible for members of an organisation leads to a 404 error on the detail page.

**To Reproduce**
1. Create Resource
2. Make public -> is shown in the results, detail page is shown without an issue
3. Make visible only for organisation members
4. Resource is shown in search results
5. Detail page leads to error
![grafik](https://user-images.githubusercontent.com/75273091/130745560-426fe532-23b8-4f1f-93f1-0ac8c161a03a.png)

**Expected behavior**
Detail page loads without error

**Setup**
 - Device: PC
 - OS & Version: Windows 10 Pro
 - Browser & Version: Firefox 91.0.1

**Comment by benediktdertinger** [comment]
@johanneshochholzer this is planned behaviour. If the user is not publicly available + the user is not logged in + has not the related access role the resource is not displayed. What do you expect here instead?

We could display a page telling that you have to be logged in + have the required access roles. Everything we render here can also be indexed in search engines (if do not explicitly opt-out for this page). This way everything shown becomes public. I suggest to display an 401 Error – Unauthorized (not logged in) or 403 Error – Forbidden (if authorized but no related access role was granted to the user).

@ingowonner what do you think?

**Comment by ingowonner** [comment]
I think it depends how "exclusive / private" the resources without public access should be. The current options would be:
### Not exclusive / private
- [x] Viewable by everyone; Bookable only by selected access roles (for this we need to open up the detail pages, but block the booking module)
### Super exclusive / private
- [ ] Viewable and bookable only by selected access roles; 404 if no access (current implementation)
- [x] Viewable and bookable only by selected access roles; 401 if not logged in; 403 if logged in but missing access role

I'm not sure if the questions whether this resources should be exclusive / private was answered in the past? @johanneshochholzer @benediktdertinger

**Comment by johanneshochholzer** [comment]
Hey!
Thanks for clarification.

This is a bug, because I should be able to see the resource.
My user account:
![grafik](https://user-images.githubusercontent.com/75273091/139058309-eff272c2-bff1-45bc-a427-78b1355d130e.png)
The ressource:
![grafik](https://user-images.githubusercontent.com/75273091/139058435-470c9223-b08c-49fc-89b2-5ebc2f14b1b7.png)
The Detail page:
![grafik](https://user-images.githubusercontent.com/75273091/139058786-7fbae93a-7228-4194-bc0a-6ded4c67ca23.png)
Also the search bar isn't working today and is always empty for any search:
![grafik](https://user-images.githubusercontent.com/75273091/139058880-a4a3d83c-9b0a-4b57-96f0-f49fa9a7c462.png)

**Comment by johanneshochholzer** [comment]
Please implement the route that Ingo sketched:
401 if not logged in; 403 if logged in but missing access role
The error page should also give the needed roles such that trouble shooting can be done easily
e.g. You cannot see this page, because you need to be a member of O-NAME.
a) Please log in to identify yourself as a member of O-NAME
b) You don't have the right to view this page as you're not a member of O-NAME. Please use the (link to membership-request-form) to request membership.

**Comment by benediktdertinger** [comment]
MVP state:
401: Show 401 error page with login modal (slide in from bottom) or embedded login form -> redirect to same page after successful login
403: Show 403 error page with error message from Backend

Later on we can add further details to the error message from the API.

**Comment by ingowonner** [comment]
I was able to reproduce the bug. Will add the fix along with the new error pages.
