### ISSUE TITLE
Time Picker should round to next XXX (5 minutes or 15 min)

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#30]
**Product**
Frontend

**Describe the bug**
The time picker should round to next XXX (decision needed whether 5 or 15 min).

**To Reproduce**
1. Search for rooms
2. Open Time picker

**Expected behavior**
Only times in 5 or 15 min steps can be choosen.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/75273091/137199534-4750db7a-b4f3-4e61-9db0-946d1c2c62bb.png)

**Comment by david-ziegler** [comment]
can we close this? it's done. @benediktdertinger

**Comment by benediktdertinger** [comment]
This will be covered in: https://github.com/isarwatt/klink-issues/issues/126

**Comment by benediktdertinger** [comment]
@johanneshochholzer you can check and close it
