### ISSUE TITLE
Number fields can be set to negative values

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#32]
**Product**
Admin Frontend

**Describe the bug**
All number fields (number of people, prices) can be set to negative values by clicking on the "arrow down" button.

**Expected behavior**
The button to lower the value ("arrow down") is unavailable when the price / number of people is 0.
Also a german error text is needed.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/75273091/137200431-58f0e726-c11f-4599-8063-2c6e942f56d0.png)
![grafik](https://user-images.githubusercontent.com/75273091/137200562-f7a71395-6e61-4895-9f08-4dbbc77a3494.png)

**Comment by benediktdertinger** [comment]
Let's split this into two tasks:
1. Fix number fields by using text fields instead with numeric HTML validation. This way we loose the increment/decrement buttons which are HTML-standard and can vary highly depending on the browser. This is also recommended by MUI v5.
2. https://github.com/isarwatt/klink-issues/issues/89 for translation
