### ISSUE TITLE
Resource type field leads to irritation

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#33]
**Product**
Admin Frontend

**Describe the bug**
During resource creation the field with type invites users to type something but the field can't be changed.
This is also the case when editing a resource.

**To Reproduce**
Create resource
or
edit existing resource

**Expected behavior**
Idea:
always hide the type field
Have different submenus on the left hand side:
instead of "Liste"

- Unterkünfte
- Räume
- Gegenstände (comes later)

Each submenu item leads to a list of the corresponding resource types.
Then only one type of resource is showed and confusion should be reduced.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/75273091/137200934-f250532e-e46c-4da4-b3e2-07e1d834e213.png)
![grafik](https://user-images.githubusercontent.com/75273091/137201003-1fbf501e-0abe-4bea-84cc-c2d7884396cf.png)

**Comment by benediktdertinger** [comment]
@johanneshochholzer this field is disabled. It helps us to indicate what type of resource is displayed. In general it should not be possible to change a resource type once created. We have multiple options:
1. Add a more obvious style to the input field that it can't be edited
2. Add a tooltip or a notice below the field indicating: „Der Typ kann nicht mehr geändert werden“
3. Don't display the field as input but as text

I suggest to not over complicate things here as we are still in an MVP-mode and go for option 1. All the other options need further changes.

**Comment by johanneshochholzer** [comment]
Thanks for the proposal!
Please combine 1+2, that would be fine with me.
