### ISSUE TITLE
Add O/P/U for access / pricing

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#35]
**Product**
Admin Frontend

**Describe the bug**
There are organisations and projects on the platform.
User A who is responsible for resource Z is manager of Project C.
User A can only add prices and special access roles for Project C, but not for all the other projects available on the platform.

**To Reproduce**
1. Open existing resource with limited access role (see above)
2. Add access for organisation where you are not manager or
3. add access for project where you are not manager
4. the same for pricing

**Expected behavior**
Every admin user should be able to add access / pricing rules for all projects & organisations on the platform.

**Comment by johanneshochholzer** [comment]
Similar story:
Lena is resource manager of Gästeappartement Selma Lagerlöf.
However, she is not manager of the corresponding project RIO Gästeappartements
When she opens the resource, she sees the following:
![grafik](https://user-images.githubusercontent.com/75273091/138325178-bd77a821-3926-41af-a3b8-4d952e8723d5.png)
The project field appears to be empty.

**Comment by benediktdertinger** [comment]
Add `allAccessRoles` query param for O/P with manage access to address this need.

**Comment by benediktdertinger** [comment]
@johanneshochholzer you can check and close it
