### ISSUE TITLE
Definition of a resource (apartment) and booking options

### ISSUE THREAD

**Issue by ipreusshock** [isarwatt/klink-issues-public#37]
**Product**
Frontend

**Is your feature request related to a problem? Please describe.**
Price/cleaning of apartement
in RIO, Cleaning is normally done by the person who booked (=host)
But: cleaning  and/or clothes (linen, towels, dishcloth) can be booked optionally

**Describe the solution you'd like**
Cleaning and clothes should be offered as seperate additional options and, when selected, be added to the price
These two must be reflected in the definition of the resource as well

**Describe alternatives you've considered**

**Additional context**

**Comment by johanneshochholzer** [comment]
Transferred to further development backlog
