### ISSUE TITLE
Maximum duration of usage of resources should be more flexible

### ISSUE THREAD

**Issue by ipreusshock** [isarwatt/klink-issues-public#38]
**Product**
Admin Frontend (Resources)

**Describe the bug**
Currently only 7 days can be selected 
Our apartment may be booked for up to 14 nights
 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Device: [e.g. iPhone6 or PC/Mac]
 - OS & Version: [e.g. iOS 10]
 - Browser & Version [e.g. Firefox 45]

**Additional context**

**Comment by johanneshochholzer** [comment]
tracked in https://github.com/isarwatt/klink-issues/issues/268
