### ISSUE TITLE
Enhancement for Membership Requests

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#40]
<details>
  <summary>Previous issue (not relevant anymore)</summary>
  
  **Product**
Frontend 

**Describe the bug**
The membership request sometimes shows unwanted behaviour, see screenshots.

**To Reproduce**
1. Click on Konto > Mitgliedschaften

**Expected behavior**
see screenshots.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/75273091/138243373-ebd234ad-639b-416d-9b26-40a09ed787ba.png)
Please don't show any email-adress of the organisation, rather the adress of the organisation / project would be helpful.
This is also something that appears throughout the platform. Can we use something else than the mailadress as a description?
![grafik](https://user-images.githubusercontent.com/75273091/138243427-e11e3e84-25ba-415e-8bc3-ffcec393ae6d.png)
Can the steps be shown in two steps with the corresponding text fields?
First step (maybe also with process bar visualised): select organisations, maybe show list of available ones.
Second step: enter number
![grafik](https://user-images.githubusercontent.com/75273091/138243630-3e87942b-dedc-48b1-adbc-95e116508029.png)
Abbrechen Button is missing to exit the process, you can only leave by clicking somewhere else, which is a little unintuitive.
</details>

**Tasks**
- [x] Use address for organisation description: e.g. „Eine Straße 2, 71234 Stuttgart“. Find example in AFE `DataService`. `detail = UtilitiesService.addressString(item.address);`. Add to Utilities: `  public static addressString = ({ street, city, zipCode }: Address): string => `${street}, ${zipCode} ${city}`;`
- [x] Add wizard by using [MUI stepper (linear)](https://mui.com/components/steppers/#main-content)
_Wizard:_ 
* Steps are linear and you can only go to second step if first has been completed with two options: „XX auswählen“ and „Mitgliedsnummer“
* Headline: „XX Mitgliedschaft anfragen“ (above stepper)
_Step 1_
* Stepper
* Text: „Wähle ein(e) XX aus“
* Typeahead Select field
* Left button: „Abbrechen“ (closes the modal)
* Right button „Weiter“ (only active if selection was made)
_Step 2_
* Stepper
* Text: „Gib deine Mitgliedsnummer ein“
* Input field
* Left button: „Zurück“ (go to previous step)
* Right button „Anfragen“ (only available if membership id was entered)

**Comment by benediktdertinger** [comment]
Covered in https://github.com/isarwatt/klink-issues/issues/107
