### ISSUE TITLE
Login with not registered Emailadress - no message

### ISSUE THREAD

**Issue by klinkriocs** [isarwatt/klink-issues-public#45]
**Product**
Frontend

**Describe the bug**
Trying to login with email that is not known. There is no message that the credentials don't match with a registered user.

**To Reproduce**
1. Go to https://staging.klink.app/login
2. Fill in a wrong email adress
3. Fill the password field
4. Click on "Anmelden'"

**Expected behavior**
A error message that the credentials are not correct

**Screenshots**

**Setup (please complete the following information):**
 - Device: PC/Laptop
 - OS & Version: Windows 10
 - Browser & Version Chrome

**Comment by benediktdertinger** [comment]
This is by design. We do not want to give details about which email addresses do belong to users. Unfortunately this can also be achieved by using the register endpoint but we might secure this one with a captcha in the future if necessary.
