### ISSUE TITLE
Availability can not be configured

### ISSUE THREAD

**Issue by klinkriocs** [isarwatt/klink-issues-public#47]
**Product**
Admin Frontend

**Describe the bug**
Availability can not be added, nothing shown to do so
Only "Nachlauf" is configurable

**To Reproduce**
Create a new resource of type Unterkunft
Fill in the data on the different browser tab
Add tab no field available to add availability

**Expected behavior**
Configuration of Availability should be possible

**Screenshots**
![image](https://user-images.githubusercontent.com/93096986/138610421-b5b39196-8355-4a25-adff-fe301c4e289b.png)

**Setup (please complete the following information):**
 - Device: [e.g. iPhone6 or PC/Mac]
 - OS & Version: [e.g. iOS 10]
 - Browser & Version [e.g. Firefox 45]

**Additional context**
Organisation RIO Verein

**Comment by johanneshochholzer** [comment]
Hi Claudia,
this is currently in the pipeline and will be added soon.
we've been waiting for a package release to implement this.

**Comment by benediktdertinger** [comment]
@klinkriocs this has now been implemented and is working. Fixed via https://github.com/isarwatt/klink-issues/issues/25
