### ISSUE TITLE
new instance created, but only the id is visible, the clone itself is not visible anywhere anyhow

### ISSUE THREAD

**Issue by klinkriocs** [isarwatt/klink-issues-public#48]
**Product**
Admin Frontend

**Describe the bug**
new instance created, but only the id is visible, the clone itself is not visible anywhere anyhow

**Expected behavior**
That something can be done with a clone. Only ids of clones are listed, but they don't offer any action, only the id can be changed

**Comment by anjarichard** [comment]
Creating instances is currently not working well. This topic will be retested in the next days and then new tickets will be created for the issues. This one will be closed.
