### ISSUE TITLE
Price not removable

### ISSUE THREAD

**Issue by klinkriocs** [isarwatt/klink-issues-public#49]
**Product**
Admin Frontend?

**Describe the bug**
Preis for "Geschäftlich" can not be removed

**To Reproduce**
G-Appartment(only internal) -> Preise 

**Expected behavior**
Prices should only be configurable for groups the Unterkunft is visible

**Additional context**
Tested with Organisation RIO Verein,

**Comment by anjarichard** [comment]
Not reproducible in the current version on staging, so issue will be closed.
