### ISSUE TITLE
Login Symbol missing

### ISSUE THREAD

**Issue by johanneshochholzer** [isarwatt/klink-issues-public#5]
**Product**
Admin Frontend

**Describe the bug**
Login Symbol missing in the upper right corner
![grafik](https://user-images.githubusercontent.com/75273091/131487546-bdb9aa6a-dc4f-4eb1-bfdb-7404c1cffe59.png)

**Comment by benediktdertinger** [comment]
Fixed via https://github.com/isarwatt/klink-issues/issues/86
