### ISSUE TITLE
Searching popup shows strange behavior

### ISSUE THREAD

**Issue by klinkriocs** [isarwatt/klink-issues-public#51]
**Product**
Admin Frontend?

**Describe the bug**
Search is not executed

**To Reproduce**
![image](https://user-images.githubusercontent.com/93096986/138611665-3f5c0f1b-90d2-409e-96bb-a56ee30ee8a7.png)
RIO was already filled, I did some searches before
Neither adding a blank nor Enter initiated a search

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Device: [e.g. iPhone6 or PC/Mac]
 - OS & Version: [e.g. iOS 10]
 - Browser & Version [e.g. Firefox 45]

**Additional context**

**Comment by johanneshochholzer** [comment]
duplicate with #20

**Comment by anjarichard** [comment]
Not reproducible in the current version on staging, so issue will be closed.
