### ISSUE TITLE
Inhalte nicht gefunden - 404 for internal resource (only visible for O / P)

### ISSUE THREAD

**Issue by klinkriocs** [isarwatt/klink-issues-public#54]
**Product**
Frontend

**Describe the bug**
listed resource selected but not shown

**To Reproduce**
1. Click on the listet g-appartmentonly-internal 
2. See error

**Expected behavior**
more details of the appartment should be shown

**Screenshots**
![image](https://user-images.githubusercontent.com/93096986/138612602-95cd2429-9301-4e8d-9a8c-d72ad5866775.png)

**Comment by johanneshochholzer** [comment]
Duplicate of #3
