### ISSUE TITLE
Unterkunft not listed

### ISSUE THREAD

**Issue by klinkriocs** [isarwatt/klink-issues-public#55]
**Product**
Frontend 

**Describe the bug**
G-Appartment (öffentlich) not listed on the overview but found when search with the search functio

**Expected behavior**
as G-Appartment (öffentlich) is confired as visible for all, it should be listed in the overview.

**Comment by johanneshochholzer** [comment]
@ingowonner 
This is a visibility issue similar to #3

**Comment by johanneshochholzer** [comment]
Duplicate of #3
