### ISSUE TITLE
Rooms can be booked for a day after time for check in is over

### ISSUE THREAD

**Issue by klinkriocs** [isarwatt/klink-issues-public#56]
**Product**
Frontend

**Describe the bug**
Rooms can be booked for a day after time for check in is over

**To Reproduce**
1. Wait until time for check-in is over
2. Select a room to book (with price 0€)
3. Book for the current day

**Expected behavior**
Booking should be rejected or at least a warning that check in is over and that therefore the booking is only a reservation or something similar

**Screenshots**
![image](https://user-images.githubusercontent.com/93096986/138613064-2fce7957-ac8d-40f3-b2d3-5d68b0816cb5.png)

**Comment by anjarichard** [comment]
Not reproducible anymore: 
![image](https://user-images.githubusercontent.com/98964206/155541315-9b1bce79-d62c-449f-b036-73b5271b81b8.png)
Ticket will be closed
