### ISSUE TITLE
On Buchungsübersicht all button have no effect

### ISSUE THREAD

**Issue by klinkriocs** [isarwatt/klink-issues-public#58]
**Product**
Frontend 

**Describe the bug**
On Buchungsübersicht all button have no effect

**To Reproduce**
1. Book a room
2. on "Buchungsbestätigung 
3. click on the Download buttons or "Zu meinen Buchungen"

**Expected behavior**
Download should be executed, Clicking on "ZU meinen Buchungen" should leed to an overview

**Screenshots**
![image](https://user-images.githubusercontent.com/93096986/138638112-6c433675-c573-4204-a169-bc5550a3a515.png)

**Setup (please complete the following information):**
 - Device: PC
 - OS & Version: Windows 10
 - Browser & Version Chrome Version 95.0.4638.54 (Offizieller Build) (64-Bit)
 - 
**Additional context**

**Comment by benediktdertinger** [comment]
These features have not been implemented yet and will be hidden via https://github.com/isarwatt/klink-issues/issues/98 for now
