### ISSUE TITLE
Room can be booked allthough another booking done for the same time frame

### ISSUE THREAD

**Issue by klinkriocs** [isarwatt/klink-issues-public#59]
**Product**
Frontend 

**Describe the bug**
Room can be booked allthough another booking done for the same time frame

**To Reproduce**
1. Book a room
2. After booking confirmation Email arrives book again the sam room for the same time frame

**Expected behavior**
Second booking should be rejected

**Screenshots**

**Setup (please complete the following information):**
 - Device: [e.g. iPhone6 or PC/Mac]
 - OS & Version: [e.g. iOS 10]
 - Browser & Version [e.g. Firefox 45]

**Additional context**

**Comment by anjarichard** [comment]
Issue not reproducible as the same room can't be booked twice for the same time frame. The calender is blocked and/or warning message is displayed: 
![image](https://user-images.githubusercontent.com/98964206/155539040-134b7e46-cbfc-4713-9b0e-ff51b6115318.png)
Ticket will be closed.
