### ISSUE TITLE
Booking time for a room on the "Buchungsbestätigung" is different from time booked

### ISSUE THREAD

**Issue by klinkriocs** [isarwatt/klink-issues-public#60]
**Product**
Frontend

**Describe the bug**
Booking time for a room on the "Buchungsbestätigung" is different from time booked

**To Reproduce**
1. Choose a room for 7:40 to 8:40
2. finisch the booking

**Expected behavior**
Confirmed time should be the same as the choosen time

**Screenshots**
![image](https://user-images.githubusercontent.com/93096986/138638964-3631fcf8-c45c-4cd7-978b-0fb5460dd868.png)

Setup (please complete the following information):

Device: PC
OS & Version: Windows 10
Browser & Version Chrome Version 95.0.4638.54 (Offizieller Build) (64-Bit)

**Comment by johanneshochholzer** [comment]
See #44 
@benediktdertinger How are the times currently calculated?

**Comment by benediktdertinger** [comment]
Has been fixed via https://github.com/isarwatt/klink-issues/issues/94
