### ISSUE TITLE
Easier Access for project deletion

### ISSUE THREAD

**Issue by Inergert** [isarwatt/klink-issues-public#7]
**Product**
Admin Frontend

**Is your feature request related to a problem? Please describe.**
You first have to put a check mark in front of the object to be deleted, then a button "Remove" appears above it.

**Describe the solution you'd like**
It would be better if there was a recycle bin icon next to the pencil on the right-hand side of the actions, which you can see at first glance.

![Projekt löschen_vs2](https://user-images.githubusercontent.com/89545637/134148698-19adbc5d-0f27-44aa-bb13-1682e653c4d8.jpg)

**Comment by johanneshochholzer** [comment]
transferred to https://github.com/isarwatt/klink-issues/issues/269
