### ISSUE TITLE
Test-Booking for "Großer Gemeinsaftsraum" but for 0 €

### ISSUE THREAD

**Issue by jefinger** [isarwatt/klink-issues-public#8]
**Product**
Frontend

**Describe the bug**
Test-Booking for "Großer Gemeinsaftsraum" but for 0 €

**To Reproduce**
1. Test-Buchung des Großen Gemeinschaftsraums war möglich, allerding für 0 € (siehe Screen-Shot unten...) 01.09. - 02.09.
![21-08-30_Test-Buchung_Großer_Gemeinschaftsraum_1](https://user-images.githubusercontent.com/54006550/134186074-3ecdbd8d-6528-4129-84b5-621703247d6d.GIF)

2. klick auf „Großer Gemeinschaftsraum“
![21-08-30_Test-Buchung_Großer_Gemeinschaftsraum_2](https://user-images.githubusercontent.com/54006550/134186315-ff0c252c-eada-48c1-aa10-86d4a96e2d99.GIF)

3. immernoch 0€ pro Nach *2 = 0€ gesamt
klick auf „ZUR BUCHUNGSÜBERSICHT“
![21-08-30_Test-Buchung_Großer_Gemeinschaftsraum_3](https://user-images.githubusercontent.com/54006550/134186593-a5d25d87-6ada-4fa1-9f0d-fafc47d0c751.GIF)

4. 0 €
5. 

**Expected behavior**
I want to see a prize not 0 €

**Screenshots**
siehe oben,,,
![21-08-30_Test-Buchung_Großer_Gemeinschaftsraum_4](https://user-images.githubusercontent.com/54006550/134189130-3524ba13-5e83-4f7d-a495-5fb3fca9fb29.GIF)
![21-08-30_Test-Buchung_Großer_Gemeinschaftsraum_5](https://user-images.githubusercontent.com/54006550/134189179-ea6bc5af-eb32-4b69-bc5b-015743f77f68.GIF)

**Setup (please complete the following information):**
 - Device: PC
 - OS & Version: Win 10
 - Browser & Version Firefox 92.0

**Additional context**

**Comment by johanneshochholzer** [comment]
Hallo Jonas,
Danke für dein Feedback.
Der Preis wurde von den Administratoren für die Ressource (Claudia oder Irene) auf 0 € gesetzt, daher konntest du die Buchung kostenlos durchführen.

**Comment by jefinger** [comment]
I ich bin mir fast sicher das Claudia und Irene den großen gemeinschaftsraum nicht für 0 € eingezahlt haben

**Comment by jefinger** [comment]
Daher würde ich darum bitten das Ticket noch einmal zu öffnen..

**Comment by johanneshochholzer** [comment]
![grafik](https://user-images.githubusercontent.com/75273091/139591999-52483558-8610-48ba-b49e-24d722b67c6e.png)
Diese Preise wurden in der Verwaltung hinterlegt, daher passt alles soweit.
