### ISSUE TITLE
Name des Gästeappartements ist falsch

### ISSUE THREAD

**Issue by ipreusshock** [isarwatt/klink-issues-public#9]
**Product**
Frontend

**Describe the bug**
Das erste Gästeapartment in Rio heißt 
**Selma Lagerlöf**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - Device: [e.g. iPhone6 or PC/Mac]
 - OS & Version: [e.g. iOS 10]
 - Browser & Version [e.g. Firefox 45]

**Additional context**

**Comment by johanneshochholzer** [comment]
Hallo Irene,
Du bist jetzt Ressourcen-Admin und kannst die Texte selbst bearbeiten.
